query($owner: String!, $name: String!, $cursor: String) {
  repository(owner: $owner, name: $name) {
    pullRequests(states: [MERGED, CLOSED], first: 100, after: $cursor, orderBy: {field: CREATED_AT, direction: DESC}) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        title
        createdAt
        mergedAt
        closedAt
        additions
        deletions
        changedFiles
        bodyText
        merged
        state
        author {
          login
        }
        comments {
          totalCount
        }
        reviewThreads(first: 20) {
          totalCount
        }
        reviews(first: 20) {
          nodes {
            author {
              login
              __typename
            }
            submittedAt
          }
        }
      }
    }
  }
}
