query($owner: String!, $name: String!, $cursor: String) {
  repository(owner: $owner, name: $name) {
    pullRequests(
      states: [MERGED, CLOSED], 
      first: 100, 
      after: $cursor, 
      orderBy: {field: CREATED_AT, direction: DESC}
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        number
        title
        state
        createdAt
        mergedAt
        closedAt
        additions
        deletions
        changedFiles
        bodyText
        reviews(first: 100) {
          totalCount
          nodes {
            author {
              login
              __typename
            }
            submittedAt
          }
        }
        comments(first: 100) {
          totalCount
          nodes {
            author {
              login
              __typename
            }
          }
        }
      }
    }
  }
}
