query ($after: String) {
  search(query: "stars:>1 sort:stars-desc", type: REPOSITORY, first: 10, after: $after) {
    edges {
      node {
        ... on Repository {
          name
          nameWithOwner
          createdAt
          updatedAt
          primaryLanguage {
            name
          }
          pullRequests(states: [MERGED, CLOSED]) {
            totalCount
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}